name: tayf_sozluk_pro
description: "Tayf Sözlük & Dil Öğrenme Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: any
  cloud_firestore: any
  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_tts: ^4.2.1
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  csv: ^6.0.0
  share_plus: ^10.0.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  fl_chart: ^0.68.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.0
  image_picker: ^1.1.2
  http: ^1.2.0
  archive: ^3.4.3
  
  easy_localization: ^3.0.3     
  sentry_flutter: ^7.14.0       # ÇÖZÜM: Kotlin 1.6 derleme hatasını önleyen kararlı sürüm
  flutter_riverpod: ^2.4.9      
  get_it: ^7.6.4                
  home_widget: ^0.9.3           

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/test_paket.json
    - assets/EN-TR_tayf.txt
    - assets/Babylon_English_Turkish_donustu.csv
    - assets/Babylon_Turkish_English_donustu.csv
    - assets/ic_launcher.png 
    - assets/Free-KH.txt
    - assets/wordnet/wordnet_data.zip
    - assets/biohazardicon.webp
