name: tayf_sozluk_pro
description: "Tayf Sözlük & Dil Öğrenme Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_tts: ^4.2.1
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  csv: ^6.0.0
  share_plus: ^10.0.0
  # KESİN ÇÖZÜM: Yeni Nesil Isar Veritabanı
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Isar veritabanı tablolarını derlemek için gerekli
  build_runner: ^2.4.13
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/test_paket.json
    - assets/EN-TR_tayf.txt
    - assets/Babylon_English_Turkish_donustu.csv
    - assets/Babylon_Turkish_English_donustu.csv
    - assets/Free-KH.txt
